services:
  - type: web
    name: online-speed-test-backend
    env: go
    buildCommand: go build -o main ./cmd/api
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true
